### ISSUE TITLE
Import from external file problems with end line characters.

### ISSUE THREAD

**Issue by wjvanpatten** [connormeredithcu/Meredith_CSCI2270_FinalProject#2]
When importing a .txt file the program has some trouble with end line characters (there might be a cin(ignore) needed or something.

For example the following text file:

first primary uno
second secondary dos
third tertiary tres

Imports first as "irst," second as "econd," and third as "hird."

Currently working on this. This will be my phase 3 contribution.

**Comment by wjvanpatten** [comment]
Change of plans, I can't easily make changes to this program.

I don't know how to make another executable like the one in debug. 

I'm going to visit Rhonda tomorrow to look into this. 

Though I think I've narrowed down the location of the bug:

In Utilities.cpp under the funciton ReadFileSentences the following code appears

```
string line;
while (getline(infile, line))
{
    g->AddSentence(line);
}
```

there might need to be a cin.ignore somewhere in there. If the bug isn't there I think its here: 

void ResponseHandler::AddSentence(string sentence)
{
    if (sentence == "")
    {
        return;
    }

Pretty sure the  " " has something to do with it.

**Comment by connormeredithcu** [comment]
Hi again. Thank you for finding this issue!

Which version are you using?

Several things:
1. If you can build the program, then you can also make a new executable (I think.) it should replace the one in the bin folder after building.
2. Consider removing the two cin.ignore() statements in the conditionals in main and putting a new cin.ignore() statement in a line directly following the cin>>x line in main. I think I'm using cin.ignore to trash TOO MANY characters rather than not enough characters so we see the missing first letters? Please let me know if you try this and how it goes!

**Comment by wjvanpatten** [comment]
Went to Rhonda and got this compiling issue figured out. Working on debugging now

**Comment by wjvanpatten** [comment]
Alright. I think the file import bug is actually an artifact of something being wrong with my terminal/code blocks.

Consequently I've decided to drop that and added an option on the main menu which provides the user with the option of inputting multiple sentences (essentially the same thing as interact, except without replies).

**Comment by connormeredithcu** [comment]
Alright. I'm sorry you can't get it to work (if you wanted to fix it just on your end, you could change the save and quit function to add a space character to the beginning of saved lines)

I'm excited to see it.
